
- name: Download Pushover Script
  hosts: genOneBots
  tasks:
    - name: Create Folder
      file:
        path: /home/smurf/freqtrade/user_data/strategies/pushover
        state: directory
    - name: Download Kucoin Pairs File
      get_url:
        url: https://raw.githubusercontent.com/clutch70/pushover/main/pushover.py
        dest: /home/smurf/freqtrade/user_data/strategies/pushover
        mode: '0440'
        force: yes
    - name: Transfer API Token
      copy:
        src: /playbooks/files/pushover_api
        dest: /home/smurf/freqtrade/user_data/strategies/pushover/pushover_api
        decrypt: yes
