
- name: Full Update Freqtrade
  hosts: ftProd
  tasks:
    - name: Get Database IP
      shell: 'echo $FTDBIP'
      register: FTDBIP
    - name: Get Database Password
      shell: 'echo $FTDBPW'
      register: FTDBPW
    - debug: msg="The FTDBIP is {{  FTDBIP.stdout  }}"
    - name: Stop FT Containers
      command: docker-compose -f /bot/freqtrade/docker-compose.yml down
    - name: Update Bot Config
      script: "/scripts/updateFtConfig.sh"
    - name: Download Frogtrade CLI Dash
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinityData/main/kucoin-usdt-static.json
        dest: /bot/freqtrade/user_data/clidash.zip
        mode: g=rw,o=rw
    - name: Build Freqtrade
      command: docker-compose -f /bot/freqtrade/docker-compose.yml build
    - name: Pull ExchangeProxy
      command: docker-compose -f /bot/freqtrade/docker-compose.yml pull
    - name: Remove Old NFI Strats
      become: no
      file:
        path:
          - /bot/freqtrade/user_data/strategies/NostalgiaForInfinityX.py
          - /bot/freqtrade/user_data/strategies/NostalgiaForInfinityXShort.py
          - /bot/freqtrade/user_data/strategies/NostalgiaForInfinityXSwing.py
        state: absent
    - name: Download NFI Short
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinity/short/NostalgiaForInfinityX.py
        dest: /bot/freqtrade/user_data/strategies/NostalgiaForInfinityXShort.py
        mode: g=rw,o=rw
    - name: Download NFI Swing
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinity/swing/NostalgiaForInfinityX.py
        dest: /bot/freqtrade/user_data/strategies/NostalgiaForInfinityXSwing.py
        mode: g=rw,o=rw
    - name: Download NFI Normal
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinity/main/NostalgiaForInfinityX.py
        dest: /bot/freqtrade/user_data/strategies/NostalgiaForInfinityX.py
        mode: g=rw,o=rw
    - name: Download Kucoin Blacklist
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinity/main/configs/blacklist-kucoin.json
        dest: /bot/freqtrade/user_data/configs/pairlists/blacklist-kucoin.json
        mode: g=rw,o=rw
    - name: Download Kucoin Whitelist
      become: no
      get_url:
        url: https://raw.githubusercontent.com/clutch70/NostalgiaForInfinityData/main/kucoin-usdt-static.json
        dest: /bot/freqtrade/user_data/configs/pairlists/kucoin-usdt-static.json
        mode: g=rw,o=rw
    - name: Start Freqtrade
      command: docker-compose -f /bot/freqtrade/docker-compose.yml up -d
