
- name: Download NostalgiaForInfinityX to FreqTrade Bots
  hosts: genOneBots
  tasks:
    - name: Remove Old NFI
      file:
        path: /home/smurf/freqtrade/user_data/strategies/NostalgiaForInfinityX.py
        state: absent
    - name: Download
      get_url:
        url: https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX.py
        dest: /home/smurf/freqtrade/user_data/strategies/NostalgiaForInfinityX.py
        mode: '0440'
    - name: Restart Freqtrade
      command: docker restart freqtrade